<?php

return [
    'status' => [
        'TRANSFER_STATUS_PENDING' =>'1',
        'TRANSFER_STATUS_PROCESSING' =>'2',
        'TRANSFER_STATUS_COLLECTING' =>'22',
        'TRANSFER_STATUS_ERROR' =>'4',
        'TRANSFER_STATUS_CANCELLED' =>'0',
        'TRANSFER_STATUS_COMPLETED' =>'3',
        'TRANSFER_STATUS_RETRY' =>'5',
        'TRANSFER_STATUS_NO_NETWORK' =>'6',
        'TRANSFER_STATUS_GET_BALANCE' =>'7',
        'TRANSFER_STATUS_GET_CLIENT_NAME' =>'8',
        'TRANSFER_STATUS_REFUNDED' =>'10',
        'TRANSFER_STATUS_RETRIEVED_CLIENT_NAME' =>'200',
        'TRANSFER_STATUS_UPDATED_BALANCE' =>'202'
    ], 
];